baseURL = "https://0xl33t.netlify.app/"
languageCode = "en-us"
title = "0xL33T Blog"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  images = ["Static/favicon.ico"]
  keywords = ["cybersecurity", "CTF", "ethical hacking", "infosec"]

  [params.homeInfoParams]
    Title = "🛡️ About 0xL33T"
    Content = """0xL33T is a cybersecurity blog dedicated to delivering deep technical insights, practical research, and real-world applications across the security landscape. With a strong focus on areas like Digital Forensics & Incident Response (DFIR), Web Exploitation, Cryptography, and Offensive Security, the blog is a hub for enthusiasts and professionals seeking high-quality, no-fluff content.

The goal of 0xL33T is to:

🧠 Share knowledge through detailed write-ups and guides

⚔️ Explore real-world attack and defense techniques

🔍 Promote a deeper understanding of cyber threats and defense strategies

Whether you're an aspiring analyst, red teamer, or just curious about how the digital world is secured (or broken), 0xL33T is your home for sharp, technical, and practical cybersecurity content."""

[params.assets]
  favicon = "Static/favicon.ico"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "team"
    name = "Team"
    url = "/team/"
    weight = 40
