baseURL = "https://0xl33t.netlify.app/"
languageCode = "en-us"
title = "0xL33T Blog"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  homeInfoParams = { Title = "0xL33T Blog", Content = "Cybersecurity and CTFs." }
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
